name: Build and Deploy Code

on: 
  push:
    branches:
      - "main"

jobs:
  build:
    environment:
      name: testing
    env:
      MONGO_URL: ${{secrets.MONGO_URL}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      JWT_ACCESS_TOKEN_LIFETIME: ${{secrets.JWT_ACCESS_TOKEN_LIFETIME}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      JWT_REFRESH_TOKEN_LIFETIME: ${{secrets.JWT_REFRESH_TOKEN_LIFETIME}}
      NODE_ENV: ${{secrets.NODE_ENV}}
      REDIS_URL: ${{secrets.REDIS_URL}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}
      CORS_ORIGIN: ${{secrets.CORS_ORIGIN}}
      REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}



